"use client";

import { useState, useEffect } from "react";
import DashboardLayout from "@/components/DashboardLayout";

interface ScheduledItem {
  id: string;
  type: string;
  platform: string;
  topic?: string;
  text_content?: string;
  status: string;
  scheduled_at?: string;
}

const DAYS_OF_WEEK = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export default function CalendarPage() {
  const [items, setItems] = useState<ScheduledItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadSchedule() {
      try {
        const res = await fetch("/api/content");
        if (res.ok) {
          const data = await res.json();
          setItems(data.content || []);
        }
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    loadSchedule();
  }, []);

  // Group posts by day of the week
  const groupedByDay: Record<string, ScheduledItem[]> = {};
  DAYS_OF_WEEK.forEach((d) => (groupedByDay[d] = []));

  items.forEach((item) => {
    const d = item.scheduled_at ? new Date(item.scheduled_at) : new Date();
    const dayName = DAYS_OF_WEEK[d.getDay()];
    if (groupedByDay[dayName]) {
      groupedByDay[dayName].push(item);
    }
  });

  return (
    <DashboardLayout>
      <div className="card fade-in" style={{ marginBottom: 24 }}>
        <div className="card-header">
          <div>
            <div className="card-title">Social Publishing Calendar</div>
            <div className="card-subtitle">
              Automated posting schedule generated by the AI Brain for InternCareerPath.
            </div>
          </div>
          <span className="badge badge-info">7-Day View</span>
        </div>
      </div>

      {loading ? (
        <div className="loading">
          <div className="spinner" />
          <span>Building publishing calendar...</span>
        </div>
      ) : (
        <div className="grid-auto" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))" }}>
          {DAYS_OF_WEEK.map((day) => {
            const dayPosts = groupedByDay[day];
            return (
              <div key={day} className="card fade-in" style={{ minHeight: 320 }}>
                <div className="card-header" style={{ marginBottom: 12, paddingBottom: 8, borderBottom: "1px solid var(--border-subtle)" }}>
                  <span className="card-title" style={{ fontSize: 14 }}>{day}</span>
                  <span className="badge badge-muted">{dayPosts.length} posts</span>
                </div>

                {dayPosts.length === 0 ? (
                  <div style={{ fontSize: 12, color: "var(--text-muted)", padding: "20px 0", textAlign: "center" }}>
                    No posts scheduled
                  </div>
                ) : (
                  <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                    {dayPosts.map((post) => (
                      <div
                        key={post.id}
                        style={{
                          background: "var(--bg-input)",
                          padding: 10,
                          borderRadius: 8,
                          borderLeft: "3px solid var(--primary)",
                        }}
                      >
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
                          <span className={`platform-icon platform-${post.platform}`} style={{ width: 22, height: 22, fontSize: 10 }}>
                            {post.platform.slice(0, 2).toUpperCase()}
                          </span>
                          <span style={{ fontSize: 10, color: "var(--text-muted)" }}>
                            {post.scheduled_at
                              ? new Date(post.scheduled_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
                              : "12:00 PM"}
                          </span>
                        </div>
                        <div style={{ fontSize: 11, color: "var(--text-secondary)", fontWeight: 500, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                          {post.topic || post.text_content?.slice(0, 30)}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </DashboardLayout>
  );
}
